import { useMemo } from 'react';
import { useUIStore } from '../stores/uiStore';

const ru = {
  common: {
    save: 'Сохранить',
    cancel: 'Отмена',
    buy: 'Купить',
    error: 'Ошибка',
    points: 'баллов',
    noChildCabinet: 'Сначала добавьте ребёнка и создайте кабинет.',
  },
  nav: {
    home: 'Главная',
    diary: 'Дневник',
    add: 'Добавить',
    shop: 'Магазин',
    history: 'История',
    stats: 'Статистика',
  },
  add: {
    title: 'Добавить активность',
    date: 'Дата активности',
    study: 'Учёба',
    sport: 'Спорт',
    behavior: 'Поведение',
    task: 'Задание',
    subject: 'Предмет',
    sportType: 'Вид спорта',
    minutes: 'Минут',
    behaviorType: 'Тип поведения',
    good: 'Хорошее',
    bad: 'Плохое',
    taskName: 'Название задания',
    taskPlaceholder: 'Например: убрать комнату',
    taskPoints: 'Баллы за задание',
    taskDone: 'Задание выполнено?',
    note: 'Примечание',
    notePlaceholder: 'Комментарий...',
    preview: '{{points}} баллов после сохранения',
    addChild: 'Добавить ребёнка',
  },
  shop: {
    title: 'Магазин',
    myRewards: 'Мои награды',
    savings: 'Копилка',
    savingsHint: 'Копилка помогает отложить баллы на крупные награды.',
    deposit: 'Положить',
    withdraw: 'Забрать',
    emptyTitle: 'Награды не добавлены',
    emptySubtitle: 'Добавьте награды или создайте новый кабинет с шаблонным магазином.',
    confirmTitle: 'Подтверждение покупки',
    confirmText: 'Купить "{{name}}" за {{points}} баллов?',
    notEnough: 'Недостаточно баллов',
    childPurchases: 'Покупки ребёнка',
    lockedUntilPeriodEnd: 'Покупки откроются после завершения периода: {{date}}',
    childOnly: 'Покупка доступна ребёнку',
    categories: {
      all: 'Все',
      money: 'Деньги',
      screen: 'Экран',
      toy: 'Игрушки',
      game: 'Игры',
      activity: 'События',
      privilege: 'Привилегии',
      other: 'Другое',
    },
  },
  history: {
    title: 'История',
    empty: 'История пустая',
    today: 'Сегодня',
    yesterday: 'Вчера',
    range: 'Период истории',
    from: 'С',
    to: 'По',
    previousPeriod: 'Прошлый период',
    currentPeriod: 'Текущий период',
    allDates: 'Все даты',
    cabinetPeriods: 'Кабинеты и архив',
    archived: 'Архив',
    filters: {
      all: 'Все',
      study: 'Учёба',
      sport: 'Спорт',
      behavior: 'Поведение',
      task: 'Задания',
    },
  },
  diary: {
    title: 'Дневник',
    premiumTitle: 'Дневник доступен в Premium',
    premiumText: 'Родитель видит расписание и быстро ставит оценку за нужный день.',
    activatePremium: 'Активировать Premium',
    paperMode: 'Неделя',
    dayMode: 'День',
    noLessons: 'Занятий нет',
    noLessonsText: 'На этот день расписание не заполнено. Возможно, это выходной.',
    daySubjects: 'Предметы на выбранный день',
    dayHint: 'Выберите предмет и поставьте оценку за нужную дату.',
    saveGrade: 'Сохранить оценку',
    gradeSaved: 'Оценка сохранена',
    gradeSavedText: '{{points}} баллов добавлено в историю.',
    gradeError: 'Не удалось сохранить оценку.',
    fromDiary: 'Добавлено из дневника',
    tempSubjectTitle: 'Разовый предмет на этот день',
    tempSubjectPlaceholder: 'Например: Информатика',
    addTempSubject: 'Добавить на дату',
    enterSubject: 'Введите название предмета.',
    tempSubjectError: 'Не удалось добавить предмет на выбранный день.',
    futureGradeError: 'Нельзя ставить оценку за будущую дату.',
    dateOutsideCabinet: 'Дата оценки должна быть внутри периода текущего кабинета.',
    subjectColumn: 'Предмет',
    categoryColumn: 'Кат.',
    gradeColumn: 'Оценка',
    pointsColumn: 'Баллы',
    weekdays: ['Воскресенье', 'Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота'],
    schoolWeekdays: ['Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота'],
  },
  duels: {
    title: 'Дуэли',
    premiumTitle: 'Дуэли доступны в Premium',
    premiumText: 'Ребёнок запускает соревнование, родитель видит статус и участников.',
    settings: 'Открыть настройки',
    childHero: 'Создай соревнование',
    parentHero: 'Контроль дуэлей',
    childHint: 'Дуэль создаёт ребёнок. Прогресс считается по активностям текущего кабинета.',
    parentHint: 'Родитель просматривает дуэли, прогресс, участников и статус завершения.',
    newDuel: 'Новая дуэль',
    startDate: 'Начало',
    endDate: 'Окончание',
    periodHint: 'Период не может выходить за кабинет: {{start}} - {{end}}',
    pointsGoal: 'Баллы',
    streakGoal: 'Серия',
    create: 'Создать дуэль',
    periodError: 'Период дуэли должен быть внутри периода текущего кабинета.',
    participant: 'Участник {{number}}',
    defaultTitle: 'Соревнование с друзьями',
    duelFallback: 'Дуэль',
    created: 'Дуэль создана',
    createdText: 'Она появилась в активных дуэлях.',
    active: 'Активна',
    finished: 'Завершена',
    progress: 'Прогресс ребёнка',
    participants: 'Участники',
    agreed: 'согласен',
    activeStatus: 'активен',
    deactivateHint: 'Отключение дуэли сработает только после согласия всех участников: {{count}}/{{total}}.',
    confirmDisable: 'Подтвердить отключение',
    complete: 'Завершить',
    completeTitle: 'Завершить дуэль?',
    completeText: 'Дуэль будет закрыта и останется в списке как завершённая.',
    noDuelsChild: 'Активных дуэлей пока нет.',
    noDuelsParent: 'У ребёнка пока нет созданных дуэлей.',
    noChildCabinet: 'Сначала выберите ребёнка и активный кабинет.',
  },
  settings: {
    title: 'Настройки',
    language: 'Язык',
    theme: 'Внешний вид',
    themeLight: 'Светлая',
    themeDark: 'Тёмная',
    themeSystem: 'Системная',
    saved: 'Настройки применены',
  },
  activity: {
    study: 'Учёба',
    sport: 'Спорт',
    behavior: 'Поведение',
    task: 'Задание',
    subject: 'Предмет',
    sportFallback: 'Спорт',
    goodBehavior: 'Хорошее поведение',
    badBehavior: 'Требует внимания',
    minutes: 'мин',
  },
  home: {
    welcome: 'Добро пожаловать!',
    addChildHint: 'Сначала добавьте ребёнка. Кабинеты и награды появятся после настройки.',
    addChild: 'Добавить ребёнка',
    signOut: 'Выйти из аккаунта',
    parentFallback: 'родитель',
    greeting: 'Привет, {{name}}!',
    parentWorkspace: 'Рабочее место родителя: {{name}}',
    childProgress: 'Твой прогресс',
    createCabinetHint: 'Для {{name}} ещё нет кабинета. Создайте период, предметы и расписание.',
    createCabinet: 'Создать кабинет',
    available: 'Доступно',
    savings: 'В копилке',
    savingsHint: 'Можно отложить в магазине',
    categories: 'Категории',
    quests: 'Квесты',
    collection: 'Коллекция',
    duels: 'Дуэли',
    recent: 'Последние активности',
    viewAll: 'Смотреть все',
    noActivities: 'Пока нет активностей',
    loading: 'Загрузка...',
    emptyHint: 'Добавьте оценку из дневника или вкладки добавления.',
    collectionNotice: 'В коллекции {{count}} карточек. Нажмите, чтобы открыть.',
    levelShort: 'Ур. {{level}}',
    level: 'Уровень',
    childLevel: 'Уровень ребёнка',
    maxLevel: 'Это максимальный уровень. Все заработанные баллы дальше остаются в прогрессе и наградах.',
    nextLevelHint: 'До следующего уровня нужно ещё {{missing}} баллов. Следующий уровень: {{name}}.',
    period: 'Период',
    periodPointsLabel: 'Баллы за период',
    periodBonus: 'Бонус за период',
    periodPlanDone: 'План периода выполнен.',
    periodMostlyDone: 'Период выполнен минимум на 75%.',
    periodFinished: 'Период завершён',
    periodFinishedText: 'Период кабинета "{{name}}" закончился {{date}}. Хотите подвести итоги?',
    later: 'Позже',
    summarize: 'Подвести итоги',
    currencyEstimate: 'Примерно валюты: {{value}} {{symbol}}',
    screenEstimate: 'Ориентир экранного времени: {{minutes}} мин.',
    periodSummary: 'Итоги периода',
    periodPoints: 'Баллы за период: {{total}} / {{target}}.',
    periodBonusLine: 'Бонус за итог: +{{bonus}} баллов.',
    afterPeriodHint: 'После завершения можно открыть магазин и создать новый период.',
    finish: 'Завершить',
    finishArchive: 'Завершить и в архив',
  },
};

const en: typeof ru = {
  common: {
    save: 'Save',
    cancel: 'Cancel',
    buy: 'Buy',
    error: 'Error',
    points: 'points',
    noChildCabinet: 'Add a child and create a cabinet first.',
  },
  nav: {
    home: 'Home',
    diary: 'Diary',
    add: 'Add',
    shop: 'Shop',
    history: 'History',
    stats: 'Stats',
  },
  add: {
    title: 'Add activity',
    date: 'Activity date',
    study: 'Study',
    sport: 'Sport',
    behavior: 'Behavior',
    task: 'Task',
    subject: 'Subject',
    sportType: 'Sport type',
    minutes: 'Minutes',
    behaviorType: 'Behavior type',
    good: 'Good',
    bad: 'Bad',
    taskName: 'Task name',
    taskPlaceholder: 'Example: clean the room',
    taskPoints: 'Task points',
    taskDone: 'Task completed?',
    note: 'Note',
    notePlaceholder: 'Comment...',
    preview: '{{points}} points after saving',
    addChild: 'Add child',
  },
  shop: {
    title: 'Shop',
    myRewards: 'My rewards',
    savings: 'Savings',
    savingsHint: 'Savings help reserve points for bigger rewards.',
    deposit: 'Deposit',
    withdraw: 'Withdraw',
    emptyTitle: 'No rewards yet',
    emptySubtitle: 'Add rewards or create a cabinet with a shop template.',
    confirmTitle: 'Purchase confirmation',
    confirmText: 'Buy "{{name}}" for {{points}} points?',
    notEnough: 'Not enough points',
    childPurchases: 'Child purchases',
    lockedUntilPeriodEnd: 'Purchases open after the period ends: {{date}}',
    childOnly: 'Purchases are available to the child',
    categories: {
      all: 'All',
      money: 'Money',
      screen: 'Screen',
      toy: 'Toys',
      game: 'Games',
      activity: 'Events',
      privilege: 'Perks',
      other: 'Other',
    },
  },
  history: {
    title: 'History',
    empty: 'History is empty',
    today: 'Today',
    yesterday: 'Yesterday',
    range: 'History period',
    from: 'From',
    to: 'To',
    previousPeriod: 'Previous period',
    currentPeriod: 'Current period',
    allDates: 'All dates',
    cabinetPeriods: 'Cabinets and archive',
    archived: 'Archive',
    filters: {
      all: 'All',
      study: 'Study',
      sport: 'Sport',
      behavior: 'Behavior',
      task: 'Tasks',
    },
  },
  diary: {
    title: 'Diary',
    premiumTitle: 'Diary is available in Premium',
    premiumText: 'Parents see the schedule and quickly add a grade for the selected day.',
    activatePremium: 'Activate Premium',
    paperMode: 'Week',
    dayMode: 'Day',
    noLessons: 'No lessons',
    noLessonsText: 'The schedule is empty for this day. It may be a day off.',
    daySubjects: 'Subjects for selected day',
    dayHint: 'Choose a subject and add a grade for the selected date.',
    saveGrade: 'Save grade',
    gradeSaved: 'Grade saved',
    gradeSavedText: '{{points}} points added to history.',
    gradeError: 'Could not save grade.',
    fromDiary: 'Added from diary',
    tempSubjectTitle: 'One-time subject for this day',
    tempSubjectPlaceholder: 'Example: Computer science',
    addTempSubject: 'Add to date',
    enterSubject: 'Enter a subject name.',
    tempSubjectError: 'Could not add the subject for the selected day.',
    futureGradeError: 'You cannot add a grade for a future date.',
    dateOutsideCabinet: 'The grade date must be inside the current cabinet period.',
    subjectColumn: 'Subject',
    categoryColumn: 'Cat.',
    gradeColumn: 'Grade',
    pointsColumn: 'Points',
    weekdays: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    schoolWeekdays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  },
  duels: {
    title: 'Duels',
    premiumTitle: 'Duels are available in Premium',
    premiumText: 'The child starts a challenge, and the parent sees status and participants.',
    settings: 'Open settings',
    childHero: 'Create a challenge',
    parentHero: 'Duel control',
    childHint: 'The child creates the duel. Progress is counted from current cabinet activity.',
    parentHint: 'Parents review duels, progress, participants and completion status.',
    newDuel: 'New duel',
    startDate: 'Start',
    endDate: 'End',
    periodHint: 'The period cannot exceed the cabinet: {{start}} - {{end}}',
    pointsGoal: 'Points',
    streakGoal: 'Streak',
    create: 'Create duel',
    periodError: 'The duel period must be inside the current cabinet period.',
    participant: 'Participant {{number}}',
    defaultTitle: 'Competition with friends',
    duelFallback: 'Duel',
    created: 'Duel created',
    createdText: 'It appeared in active duels.',
    active: 'Active',
    finished: 'Finished',
    progress: 'Child progress',
    participants: 'Participants',
    agreed: 'agreed',
    activeStatus: 'active',
    deactivateHint: 'The duel turns off only after all participants agree: {{count}}/{{total}}.',
    confirmDisable: 'Confirm disable',
    complete: 'Finish',
    completeTitle: 'Finish duel?',
    completeText: 'The duel will close and remain in the list as finished.',
    noDuelsChild: 'No active duels yet.',
    noDuelsParent: 'This child has no created duels yet.',
    noChildCabinet: 'Select a child and active cabinet first.',
  },
  settings: {
    title: 'Settings',
    language: 'Language',
    theme: 'Appearance',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'System',
    saved: 'Settings applied',
  },
  activity: {
    study: 'Study',
    sport: 'Sport',
    behavior: 'Behavior',
    task: 'Task',
    subject: 'Subject',
    sportFallback: 'Sport',
    goodBehavior: 'Good behavior',
    badBehavior: 'Needs attention',
    minutes: 'min',
  },
  home: {
    welcome: 'Welcome!',
    addChildHint: 'Add a child first. Cabinets and rewards will appear after setup.',
    addChild: 'Add child',
    signOut: 'Sign out',
    parentFallback: 'parent',
    greeting: 'Hi, {{name}}!',
    parentWorkspace: 'Parent workspace: {{name}}',
    childProgress: 'Your progress',
    createCabinetHint: '{{name}} does not have a cabinet yet. Create a period, subjects and schedule.',
    createCabinet: 'Create cabinet',
    available: 'Available',
    savings: 'Savings',
    savingsHint: 'Can be saved in the shop',
    categories: 'Categories',
    quests: 'Quests',
    collection: 'Collection',
    duels: 'Duels',
    recent: 'Recent activity',
    viewAll: 'View all',
    noActivities: 'No activities yet',
    loading: 'Loading...',
    emptyHint: 'Add a grade from the diary or add tab.',
    collectionNotice: '{{count}} cards in the collection. Tap to open.',
    levelShort: 'Lv. {{level}}',
    level: 'Level',
    childLevel: 'Child level',
    maxLevel: 'This is the maximum level. Further earned points stay in progress and rewards.',
    nextLevelHint: '{{missing}} more points are needed for the next level. Next level: {{name}}.',
    period: 'Period',
    periodPointsLabel: 'Period points',
    periodBonus: 'Period bonus',
    periodPlanDone: 'Period plan completed.',
    periodMostlyDone: 'Period completed by at least 75%.',
    periodFinished: 'Period finished',
    periodFinishedText: 'Cabinet "{{name}}" ended on {{date}}. Do you want to summarize it?',
    later: 'Later',
    summarize: 'Summarize',
    currencyEstimate: 'Estimated currency: {{value}} {{symbol}}',
    screenEstimate: 'Screen time guide: {{minutes}} min.',
    periodSummary: 'Period summary',
    periodPoints: 'Period points: {{total}} / {{target}}.',
    periodBonusLine: 'Result bonus: +{{bonus}} points.',
    afterPeriodHint: 'After finishing, you can open the shop and create a new period.',
    finish: 'Finish',
    finishArchive: 'Finish and archive',
  },
};

const zh: typeof ru = {
  common: {
    save: '保存',
    cancel: '取消',
    buy: '购买',
    error: '错误',
    points: '积分',
    noChildCabinet: '请先添加孩子并创建学习档案。',
  },
  nav: {
    home: '首页',
    diary: '日记',
    add: '添加',
    shop: '商店',
    history: '历史',
    stats: '统计',
  },
  add: {
    title: '添加活动',
    date: '活动日期',
    study: '学习',
    sport: '运动',
    behavior: '行为',
    task: '任务',
    subject: '科目',
    sportType: '运动类型',
    minutes: '分钟',
    behaviorType: '行为类型',
    good: '良好',
    bad: '不好',
    taskName: '任务名称',
    taskPlaceholder: '例如：整理房间',
    taskPoints: '任务积分',
    taskDone: '任务已完成？',
    note: '备注',
    notePlaceholder: '评论...',
    preview: '保存后 {{points}} 积分',
    addChild: '添加孩子',
  },
  shop: {
    title: '商店',
    myRewards: '我的奖励',
    savings: '储蓄',
    savingsHint: '储蓄可以帮助为更大的奖励保留积分。',
    deposit: '存入',
    withdraw: '取出',
    emptyTitle: '暂无奖励',
    emptySubtitle: '添加奖励，或创建带商店模板的学习档案。',
    confirmTitle: '购买确认',
    confirmText: '用 {{points}} 积分购买“{{name}}”？',
    notEnough: '积分不足',
    childPurchases: '孩子的购买',
    lockedUntilPeriodEnd: '购买将在周期结束后开放：{{date}}',
    childOnly: '购买仅对孩子开放',
    categories: {
      all: '全部',
      money: '金钱',
      screen: '屏幕',
      toy: '玩具',
      game: '游戏',
      activity: '活动',
      privilege: '特权',
      other: '其他',
    },
  },
  history: {
    title: '历史',
    empty: '历史为空',
    today: '今天',
    yesterday: '昨天',
    range: '历史周期',
    from: '从',
    to: '到',
    previousPeriod: '上一周期',
    currentPeriod: '当前周期',
    allDates: '全部日期',
    cabinetPeriods: '档案和归档',
    archived: '归档',
    filters: {
      all: '全部',
      study: '学习',
      sport: '运动',
      behavior: '行为',
      task: '任务',
    },
  },
  diary: {
    title: '日记',
    premiumTitle: '日记仅 Premium 可用',
    premiumText: '家长可以查看课程表，并快速为指定日期添加成绩。',
    activatePremium: '启用 Premium',
    paperMode: '周',
    dayMode: '日',
    noLessons: '没有课程',
    noLessonsText: '这一天没有课程安排，可能是休息日。',
    daySubjects: '所选日期的科目',
    dayHint: '选择科目并为所选日期添加成绩。',
    saveGrade: '保存成绩',
    gradeSaved: '成绩已保存',
    gradeSavedText: '{{points}} 积分已添加到历史。',
    gradeError: '无法保存成绩。',
    fromDiary: '来自日记',
    tempSubjectTitle: '这一天的临时科目',
    tempSubjectPlaceholder: '例如：信息技术',
    addTempSubject: '添加到日期',
    enterSubject: '请输入科目名称。',
    tempSubjectError: '无法为所选日期添加科目。',
    futureGradeError: '不能为未来日期添加成绩。',
    dateOutsideCabinet: '成绩日期必须在当前档案周期内。',
    subjectColumn: '科目',
    categoryColumn: '类',
    gradeColumn: '成绩',
    pointsColumn: '积分',
    weekdays: ['星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六'],
    schoolWeekdays: ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六'],
  },
  duels: {
    title: '对决',
    premiumTitle: '对决仅 Premium 可用',
    premiumText: '孩子发起挑战，家长查看状态和参与者。',
    settings: '打开设置',
    childHero: '创建挑战',
    parentHero: '对决管理',
    childHint: '对决由孩子创建。进度来自当前学习档案中的活动。',
    parentHint: '家长查看对决、进度、参与者和完成状态。',
    newDuel: '新对决',
    startDate: '开始',
    endDate: '结束',
    periodHint: '周期不能超出档案：{{start}} - {{end}}',
    pointsGoal: '积分',
    streakGoal: '连续天数',
    create: '创建对决',
    periodError: '对决周期必须在当前档案周期内。',
    participant: '参与者 {{number}}',
    defaultTitle: '和朋友比赛',
    duelFallback: '对决',
    created: '对决已创建',
    createdText: '它已出现在活动对决中。',
    active: '进行中',
    finished: '已结束',
    progress: '孩子进度',
    participants: '参与者',
    agreed: '已同意',
    activeStatus: '活动中',
    deactivateHint: '只有所有参与者同意后，对决才会关闭：{{count}}/{{total}}。',
    confirmDisable: '确认关闭',
    complete: '结束',
    completeTitle: '结束对决？',
    completeText: '对决将关闭，并作为已结束保留在列表中。',
    noDuelsChild: '暂无活动对决。',
    noDuelsParent: '该孩子还没有创建对决。',
    noChildCabinet: '请先选择孩子和活动档案。',
  },
  settings: {
    title: '设置',
    language: '语言',
    theme: '外观',
    themeLight: '浅色',
    themeDark: '深色',
    themeSystem: '系统',
    saved: '设置已应用',
  },
  activity: {
    study: '学习',
    sport: '运动',
    behavior: '行为',
    task: '任务',
    subject: '科目',
    sportFallback: '运动',
    goodBehavior: '良好行为',
    badBehavior: '需要注意',
    minutes: '分钟',
  },
  home: {
    welcome: '欢迎！',
    addChildHint: '请先添加孩子。设置后会出现学习档案和奖励。',
    addChild: '添加孩子',
    signOut: '退出账号',
    parentFallback: '家长',
    greeting: '你好，{{name}}！',
    parentWorkspace: '家长工作区：{{name}}',
    childProgress: '你的进度',
    createCabinetHint: '{{name}} 还没有学习档案。请创建周期、科目和课程表。',
    createCabinet: '创建档案',
    available: '可用',
    savings: '储蓄',
    savingsHint: '可在商店中保留',
    categories: '分类',
    quests: '任务',
    collection: '收藏',
    duels: '对决',
    recent: '最近活动',
    viewAll: '查看全部',
    noActivities: '暂无活动',
    loading: '加载中...',
    emptyHint: '从日记或添加页面添加成绩。',
    collectionNotice: '收藏中有 {{count}} 张卡片。点击打开。',
    levelShort: '{{level}}级',
    level: '等级',
    childLevel: '孩子等级',
    maxLevel: '这是最高等级。之后获得的积分仍会保留在进度和奖励中。',
    nextLevelHint: '距离下一等级还需要 {{missing}} 积分。下一等级：{{name}}。',
    period: '周期',
    periodPointsLabel: '周期积分',
    periodBonus: '周期奖励',
    periodPlanDone: '周期计划已完成。',
    periodMostlyDone: '周期至少完成 75%。',
    periodFinished: '周期已结束',
    periodFinishedText: '档案“{{name}}”的周期已于 {{date}} 结束。要查看总结吗？',
    later: '稍后',
    summarize: '查看总结',
    currencyEstimate: '预计货币：{{value}} {{symbol}}',
    screenEstimate: '屏幕时间参考：{{minutes}} 分钟',
    periodSummary: '周期总结',
    periodPoints: '周期积分：{{total}} / {{target}}。',
    periodBonusLine: '总结奖励：+{{bonus}} 积分。',
    afterPeriodHint: '完成后可以打开商店并创建新周期。',
    finish: '完成',
    finishArchive: '完成并归档',
  },
};

const fr: typeof ru = {
  ...en,
  common: { ...en.common, save: 'Enregistrer', cancel: 'Annuler', buy: 'Acheter', error: 'Erreur', points: 'points' },
  nav: { home: 'Accueil', diary: 'Journal', add: 'Ajouter', shop: 'Boutique', history: 'Historique', stats: 'Stats' },
  settings: { ...en.settings, title: 'Parametres', language: 'Langue', theme: 'Apparence', themeLight: 'Clair', themeDark: 'Sombre', themeSystem: 'Systeme', saved: 'Parametres appliques' },
  history: { ...en.history, title: 'Historique', today: 'Aujourd hui', yesterday: 'Hier', currentPeriod: 'Periode actuelle', allDates: 'Toutes les dates', archived: 'Archive' },
};

const de: typeof ru = {
  ...en,
  common: { ...en.common, save: 'Speichern', cancel: 'Abbrechen', buy: 'Kaufen', error: 'Fehler', points: 'Punkte' },
  nav: { home: 'Start', diary: 'Tagebuch', add: 'Hinzufugen', shop: 'Shop', history: 'Verlauf', stats: 'Statistik' },
  settings: { ...en.settings, title: 'Einstellungen', language: 'Sprache', theme: 'Darstellung', themeLight: 'Hell', themeDark: 'Dunkel', themeSystem: 'System', saved: 'Einstellungen angewendet' },
  history: { ...en.history, title: 'Verlauf', today: 'Heute', yesterday: 'Gestern', currentPeriod: 'Aktueller Zeitraum', allDates: 'Alle Daten', archived: 'Archiv' },
};

const it: typeof ru = {
  ...en,
  common: { ...en.common, save: 'Salva', cancel: 'Annulla', buy: 'Compra', error: 'Errore', points: 'punti' },
  nav: { home: 'Home', diary: 'Diario', add: 'Aggiungi', shop: 'Negozio', history: 'Cronologia', stats: 'Statistiche' },
  settings: { ...en.settings, title: 'Impostazioni', language: 'Lingua', theme: 'Aspetto', themeLight: 'Chiaro', themeDark: 'Scuro', themeSystem: 'Sistema', saved: 'Impostazioni applicate' },
  history: { ...en.history, title: 'Cronologia', today: 'Oggi', yesterday: 'Ieri', currentPeriod: 'Periodo corrente', allDates: 'Tutte le date', archived: 'Archivio' },
};

const es: typeof ru = {
  ...en,
  common: { ...en.common, save: 'Guardar', cancel: 'Cancelar', buy: 'Comprar', error: 'Error', points: 'puntos' },
  nav: { home: 'Inicio', diary: 'Diario', add: 'Anadir', shop: 'Tienda', history: 'Historial', stats: 'Estadisticas' },
  settings: { ...en.settings, title: 'Ajustes', language: 'Idioma', theme: 'Apariencia', themeLight: 'Claro', themeDark: 'Oscuro', themeSystem: 'Sistema', saved: 'Ajustes aplicados' },
  history: { ...en.history, title: 'Historial', today: 'Hoy', yesterday: 'Ayer', currentPeriod: 'Periodo actual', allDates: 'Todas las fechas', archived: 'Archivo' },
};

const dictionaries = { ru, en, zh, fr, de, it, es };

const interpolate = (text: string, values?: Record<string, string | number>) =>
  Object.entries(values ?? {}).reduce((result, [key, value]) => result.replaceAll(`{{${key}}}`, String(value)), text);

export const useAppText = () => {
  const language = useUIStore((state) => state.settings.language);
  const dictionary = dictionaries[language] ?? dictionaries.ru;

  return useMemo(() => ({
    lang: language,
    text: dictionary,
    tr: (template: string, values?: Record<string, string | number>) => interpolate(template, values),
  }), [dictionary, language]);
};
